//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVEIntelAnalyzer {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    public sealed partial class IntelSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static IntelSettings defaultInstance = ((IntelSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new IntelSettings())));
        
        public static IntelSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[players] in [system] [location]")]
        public string ReadKnownSystemPlayer {
            get {
                return ((string)(this["ReadKnownSystemPlayer"]));
            }
            set {
                this["ReadKnownSystemPlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Intel: [raw]")]
        public string ReadUnknownIntel {
            get {
                return ((string)(this["ReadUnknownIntel"]));
            }
            set {
                this["ReadUnknownIntel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Additional, [count] intelligence reports")]
        public string ReadAdditionalIntelReports {
            get {
                return ((string)(this["ReadAdditionalIntelReports"]));
            }
            set {
                this["ReadAdditionalIntelReports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" tac ")]
        public string SystemNameDash {
            get {
                return ((string)(this["SystemNameDash"]));
            }
            set {
                this["SystemNameDash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public string SystemNameLetterSeparator {
            get {
                return ((string)(this["SystemNameLetterSeparator"]));
            }
            set {
                this["SystemNameLetterSeparator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public string SystemNameNumberSeparator {
            get {
                return ((string)(this["SystemNameNumberSeparator"]));
            }
            set {
                this["SystemNameNumberSeparator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[players] in [system] no visual.")]
        public string ReadKnownSystemPlayerNoVisual {
            get {
                return ((string)(this["ReadKnownSystemPlayerNoVisual"]));
            }
            set {
                this["ReadKnownSystemPlayerNoVisual"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reds in [system]")]
        public string ReadKnownSystem {
            get {
                return ((string)(this["ReadKnownSystem"]));
            }
            set {
                this["ReadKnownSystem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[system] is clear.")]
        public string ReadKnownSystemClear {
            get {
                return ((string)(this["ReadKnownSystemClear"]));
            }
            set {
                this["ReadKnownSystemClear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Solar System</string>
  <string>Звездная система</string>
  <string>Sonnensystem</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DetectSystem {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DetectSystem"]));
            }
            set {
                this["DetectSystem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>at </string>
  <string>near </string>
  <string>in </string>
  <string>the </string>
  <string>a </string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DetectIgroreWords {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DetectIgroreWords"]));
            }
            set {
                this["DetectIgroreWords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".*[keyword].*")]
        public string DetectRegexSearch {
            get {
                return ((string)(this["DetectRegexSearch"]));
            }
            set {
                this["DetectRegexSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>nv</string>\r\n  <string>no visual</string>\r\n  <string>novisual</string>\r\n</" +
            "ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DetectNoVisual {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DetectNoVisual"]));
            }
            set {
                this["DetectNoVisual"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>clear</string>
  <string>isclear</string>
  <string>clr</string>
  <string>crl</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DetectClear {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DetectClear"]));
            }
            set {
                this["DetectClear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReadUseOldSpeechGeneration {
            get {
                return ((bool)(this["ReadUseOldSpeechGeneration"]));
            }
            set {
                this["ReadUseOldSpeechGeneration"] = value;
            }
        }
    }
}
