//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVEIntelAnalyzer {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    public sealed partial class IntelSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static IntelSettings defaultInstance = ((IntelSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new IntelSettings())));
        
        public static IntelSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[intel.players.name] in [system.spell] [red.location] [intel.clear] [intel.novisu" +
            "al]")]
        public string ReadKnownIntel {
            get {
                return ((string)(this["ReadKnownIntel"]));
            }
            set {
                this["ReadKnownIntel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Intel: [intel.raw]")]
        public string ReadUnknownIntel {
            get {
                return ((string)(this["ReadUnknownIntel"]));
            }
            set {
                this["ReadUnknownIntel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Additional, {0} intelligence reports")]
        public string AdditionalIntelReports {
            get {
                return ((string)(this["AdditionalIntelReports"]));
            }
            set {
                this["AdditionalIntelReports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" tac ")]
        public string SystemNameDash {
            get {
                return ((string)(this["SystemNameDash"]));
            }
            set {
                this["SystemNameDash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".")]
        public string SystemNameLetterSeparator {
            get {
                return ((string)(this["SystemNameLetterSeparator"]));
            }
            set {
                this["SystemNameLetterSeparator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public string SystemNameNumberSeparator {
            get {
                return ((string)(this["SystemNameNumberSeparator"]));
            }
            set {
                this["SystemNameNumberSeparator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" is clear.")]
        public string IsClear {
            get {
                return ((string)(this["IsClear"]));
            }
            set {
                this["IsClear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" no visual.")]
        public string NoVisual {
            get {
                return ((string)(this["NoVisual"]));
            }
            set {
                this["NoVisual"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("  in [system.spell]")]
        public string InSystem {
            get {
                return ((string)(this["InSystem"]));
            }
            set {
                this["InSystem"] = value;
            }
        }
    }
}
