//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVEIntelAnalyzer {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    public sealed partial class IntelSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static IntelSettings defaultInstance = ((IntelSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new IntelSettings())));
        
        public static IntelSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[red.name] in [system.name] [red.location]")]
        public string ReadKnownIntel {
            get {
                return ((string)(this["ReadKnownIntel"]));
            }
            set {
                this["ReadKnownIntel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Intel: [raw.intel]")]
        public string ReadUnknownIntel {
            get {
                return ((string)(this["ReadUnknownIntel"]));
            }
            set {
                this["ReadUnknownIntel"] = value;
            }
        }
    }
}
